"""Initial migration

Revision ID: d61e787b8e1b
Revises: 
Create Date: 2025-07-31 22:30:11.221470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd61e787b8e1b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commit_data',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repo_id', sa.String(), nullable=True),
    sa.Column('commit_message', sa.Text(), nullable=True),
    sa.Column('git_diff', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commit_data_id'), 'commit_data', ['id'], unique=False)
    op.create_index(op.f('ix_commit_data_repo_id'), 'commit_data', ['repo_id'], unique=False)
    op.create_table('repositories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repositories_id'), 'repositories', ['id'], unique=False)
    op.create_index(op.f('ix_repositories_name'), 'repositories', ['name'], unique=False)
    op.create_index(op.f('ix_repositories_url'), 'repositories', ['url'], unique=True)
    op.create_table('worksheets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('sheet_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worksheets_id'), 'worksheets', ['id'], unique=False)
    op.create_index(op.f('ix_worksheets_name'), 'worksheets', ['name'], unique=False)
    op.create_index(op.f('ix_worksheets_sheet_id'), 'worksheets', ['sheet_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worksheets_sheet_id'), table_name='worksheets')
    op.drop_index(op.f('ix_worksheets_name'), table_name='worksheets')
    op.drop_index(op.f('ix_worksheets_id'), table_name='worksheets')
    op.drop_table('worksheets')
    op.drop_index(op.f('ix_repositories_url'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_name'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_id'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_index(op.f('ix_commit_data_repo_id'), table_name='commit_data')
    op.drop_index(op.f('ix_commit_data_id'), table_name='commit_data')
    op.drop_table('commit_data')
    # ### end Alembic commands ###
