"""Added LLMModel and updated indexes in models

Revision ID: d972c5f57b00
Revises: d61e787b8e1b
Create Date: 2025-08-01 12:32:58.989259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd972c5f57b00'
down_revision: Union[str, Sequence[str], None] = 'd61e787b8e1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_models',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('model_id', sa.String(), nullable=True),
                    sa.Column('provider', sa.String(), nullable=True),
                    sa.Column('api_key', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_llm_models_id'),
                    'llm_models', ['id'], unique=False)
    op.create_index(op.f('ix_llm_models_model_id'),
                    'llm_models', ['model_id'], unique=True)
    op.drop_index(op.f('ix_repositories_name'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_url'), table_name='repositories')
    with op.batch_alter_table('repositories', schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_repositories_url", ['url'])

    op.drop_index(op.f('ix_worksheets_sheet_id'), table_name='worksheets')
    with op.batch_alter_table('worksheets', schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_worksheets_sheet_id", ['sheet_id'])
    # op.create_unique_constraint(None, 'worksheets', ['sheet_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'worksheets', type_='unique')
    op.create_index(op.f('ix_worksheets_sheet_id'),
                    'worksheets', ['sheet_id'], unique=1)
    op.drop_constraint(None, 'repositories', type_='unique')
    op.create_index(op.f('ix_repositories_url'),
                    'repositories', ['url'], unique=1)
    op.create_index(op.f('ix_repositories_name'),
                    'repositories', ['name'], unique=False)
    op.drop_index(op.f('ix_llm_models_model_id'), table_name='llm_models')
    op.drop_index(op.f('ix_llm_models_id'), table_name='llm_models')
    op.drop_table('llm_models')
    # ### end Alembic commands ###
